### ISSUE TITLE
Lack implicit value for parameter writer of Seq

### ISSUE THREAD

**Issue by Ang9876** [shadaj/scalapy#162]
# Description
I tried to implement a facade of `Numpy` on my own. But I found that there is no implicit writer for `Seq` in the new version. I noticed once there was a `seqWriter`, but it has been removed.

# Simplified Code
``` scala
def array[T: ClassTag](s: T)(implicit writer: Writer[T], reader: Reader[T]): NdArray[T] =
    as[py.Dynamic].array(s).as[NdArray[T]]

np.array(Seq(1, 2, 3))
```

# Error Message
``` terminal
[error] /.../src/main/scala/Test.scala:6:19: could not find implicit value for parameter writer: me.shadaj.scalapy.readwrite.Writer[Seq[Int]]
```

**Comment by shadaj** [comment]
@Ang9876 that's a good question, indeed the `Seq[T]` writers were removed in ScalaPy 0.4. The reason for this change was the introduction of proxies as an alternative way to send Scala collections to Python, so now the decision is left to developers to use `.toPythonCopy` or `.toPythonProxy`, both of which return `py.Any` (I'm planning to refine this type to use a built-in facade soon). I would recommend having `s` be a sequence type in your facade and then calling `toPythonCopy` under the hood since the NumPy array will store a copy of all the data anyway.

One thing to note is that performance of such a conversion will unfortunately suffer a bit on the JVM due to the high overhead of copying individual elements. As discussed in #158, this is something that will require a bit more work to fix.

**Comment by Ang9876** [comment]
Thanks for your response.

But when I call `as[py.Dynamic].array(s.toPythonCopy).as[NdArray[T]]`, an another error occurs that 
```
could not find implicit value for parameter elemWriter: me.shadaj.scalapy.readwrite.Writer[T]
```

Does it mean that we can send these Scala types to Python only if we know it in the compile time?

**Comment by Ang9876** [comment]
Thank you for your response. It is very useful!

**Comment by Ang9876** [comment]
It seems that it does not work for nested `Seq`.
I have to write `np.array(Seq(Seq(1, 2, 3).toPythonCopy, Seq(4, 5, 6).toPythonCopy))` instead of `np.array(Seq(Seq(1, 2, 3), Seq(4, 5, 6))), otherwise a `writer` for `Seq` is needed again.
I think it would more convenient if the conversion is implicit.
