### ISSUE TITLE
Should be able to index into NumPy array using a tuple of indices

### ISSUE THREAD

**Issue by melton1968** [shadaj/scalapy#48]
First, great library, thanks.

Second, I am working with Numpy, but am unable to use arrayAccess to get at the underlying data using the array type:

```scala
val data = py.module("numpy").arange(10)
println(data.dtype) // int64
println(data) // [0, 1, 2, ... 9]
println(data.arrayAccess(0).as[Long]) // Exception in thread "main" scala.MatchError: 0 (of class java.lang.String)
```

All array accesses seem to come back as strings (and are automagically converted back for floating types) independent of the underly numpy array type.

Is this a feature? bug? user error of some type?

Any pointers would be appreciated.

**Comment by shadaj** [comment]
Try using the latest build of ScalaPy, `0.2.0+17-5b8100b9`, which includes a rewrite of the Python interface to directly bind to native objects instead of going through Jep. That should fix the problem you're facing!

**Comment by melton1968** [comment]
I have been using `scala-core 0.3.0`. I could not get the version you quoted to work -- the Maven artifacts seem broken. Did you really mean the `0.2.0` series? And, what is the difference between scalapy-core and scalapy?

I did try `scala-core 0.3.0+xxxxx` and everything successfully compiled, but several of my unit tests failed. The ones I investigated looked like scalapy bugs. 

Here is one example:

```scala
val module = py.module("numpy")
val a = py.global.slice(py.None, py.None, py.None)
println(a) # (None, None, None)
val b = py.global.slice(5, 15, 2)
println(a) # (5, 15, 2)
```

**Comment by shadaj** [comment]
Ah, yes, I meant ScalaPy `0.3.0+xxxxx` (looks like the README version badge is broken).

What is the expected behavior in your example? I ran it locally in a Python REPL and it seems to match ScalaPy's output pretty closely.

```
>>> print(slice(None, None, None))
slice(None, None, None)
>>> print(slice(5, 15, 2))
slice(5, 15, 2)
```

**Comment by melton1968** [comment]
Turns out the problems were only occurring in my test environment and the failure modes ranged from incorrect results to segmentation faults. I haven't been able to extract a simple example that demonstrates the failure, but here is what I have so far.

The attached code (which depends on other packages I have embedded within a larger project) should produce:

```scala
slice(None, None, None)
slice(5, 15, 2)
slice(None, None, None)
```

but instead results in:

```scala
slice(None, None, None)
slice(5, 15, 2)
slice(5, 15, 2)
```

The `uSlice` variable comes from a package object. If I uncomment the local definition, then everything works correctly. If I remove the local block, everything works correctly.

My guess is the python object pointed to by `uSlice` is being freed in the local block and I am still trying to use it.

```scala
object ComputePython extends App {
  println("ComputePython...")

  // val uSlice = py.global.slice(py.None, py.None, py.None)

  local {
    val data = np.arange(100).reshape((25, 4))
    println(data(0\, 0\).toSeq == data.toSeq)
  }

  println(uSlice)
  println(py.global.slice(5,15,2))
  println(uSlice)
}
```

**Comment by shadaj** [comment]
Hmm, not able to reproduce your code. I tried running a modified version of your example since `data(0, 0)` doesn't work since that would try to call an actual `apply` method (will create an issue to have `arrayAccess` support multiple indices). I was able to successfully run and produce the expected results.

My code:

```scala
object Test extends App {
  val np = py.module("numpy")
  val uSlice = py.global.slice(py.None, py.None, py.None)

  py.local {
    val data = np.arange(100).reshape((25, 4))
    println(data)
  }

  println(uSlice)
  println(py.global.slice(5,15,2))
  println(uSlice)
}
```

Are you using ScalaPy `0.3.0+16-e91c233e`? There were some previous versions with use-after-free bugs.

**Comment by melton1968** [comment]
Updating to `0.3.0+16` seems to have cured the test failures. Thanks.

Now I will look back at the original issue of accessing the NDAarray values.

**Comment by melton1968** [comment]
Well, moving to the latest fixed some of he issues, but now I am getting a segmentation fault from what looks like try to free a slice twice. 

I get the same problem with 0.3.0+16xxx as well as the latest code from master.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000092305390f, pid=11786, tid=0x0000000000000d03
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [Python+0x5090f]  slice_dealloc+0x2a
#
```
[hs_err_pid11786.log](https://github.com/shadaj/scalapy/files/4288903/hs_err_pid11786.log)

**Comment by bfdes** [comment]
I think we are past it, but for what it is worth the original example doesn't work for me either (on master). The error I got was different -- basically ScalaPy was calling CPython methods that don't exist on numpy arrays. If I perform the conversion at the beginning

```scala
val data = py.module("numpy").arange(10).as[Seq[Int]]
println(data(0))
```
then that runs. Presumably because it summons different `Reader` instances.

**Comment by shadaj** [comment]
Since there's a new issue #49 for the reference counting bug, I'm going to use this issue to track the limitations of `.arrayAccess` with NumPy arrays.

@bfdes the reason things don't work without the `.as[Seq[Int]]` is because without the conversion you are dealing with a dynamic Python value, so the call `data(0)` is interpreted as a call`data.apply(0)` to be run in Python. The API to perform a dynamic indexing operation would be `data.arrayAccess(...)`, but right now it only supports a single index instead a tuple of them as is often used for NumPy.

**Comment by bfdes** [comment]
@shadaj Sorry, I should have clarified that I had to use `data(0)` _because of the early conversion_.
